name: CI_CD

env:
DEPLOY_PACKAGE_NAME : "crm.zip"

on:
  push:
    branches: [ "main" ]

jobs:
  ci_part:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone this repo
        uses: action/checkout@v1
        
      - name: Create zip-package
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

      - name: Connect to server
        uses: Tofandel/ssh-server-action@v1.0.0
        with:
          hostname      : ${{ secrets.HOSTNAME }}
          user_name     : ${{ secrets.LOGIN }}
          user_password : ${{ secrets.PASSWORD }}



